### ISSUE TITLE
"esprit du corps" -> "esprit de corps"

### ISSUE THREAD

**Issue by tuskpot** [standardebooks/jane-austen_mansfield-park#1]
The phrase "esprit du corps" appears in chapter 5. This matches the page scans, but I thought the correct spelling was "esprit de corps".

[Google Ngram viewer](https://books.google.com/ngrams/graph?content=esprit+du+corps%2Cesprit+de+corps&year_start=1800&year_end=2019&corpus=26&smoothing=3&direct_url=t1%3B%2Cesprit%20du%20corps%3B%2Cc0%3B.t1%3B%2Cesprit%20de%20corps%3B%2Cc0#t1%3B%2Cesprit%20du%20corps%3B%2Cc0%3B.t1%3B%2Cesprit%20de%20corps%3B%2Cc0) appears to agree that "de" is more common.

Merriam Webster has an entry for [esprit de corps](https://www.merriam-webster.com/dictionary/esprit%20de%20corps), but nothing for "esprit du corps".

So, it looks like this is an old-fashioned spelling that could be updated. I don't speak French, though, so I might be missing something. Because I'm not confident, I'm raising it as an issue instead of submitting a pull request.

**Comment by acabal** [comment]
I agree, and I've made the update. Thanks!
